name: 'AWS CDK Deploy Action'
description: 'Deploy AWS CDK Stack'
branding:
    icon: 'upload-cloud'
    color: 'blue'
inputs:
    AWS_ROLE_NAME:
        required: false
        description: 'Role name with permissions for the deployment'
    INFRASTRUCTURE_PATH:
        required: false
        description: 'Local path where cdk infrastructure code lives'
        default: './infrastructure'
    AWS_STACK_NAME:
        required: true
        description: 'Name of the stack'
    AWS_REGION:
        required: false
        description: 'Target region for the deployment'
        default: eu-west-1
    CUSTOM_BOOTSTRAP_ARGUMENTS:
        required: false
        description: 'Comma-separated list of user-defined arguments for bootstrapping'
        default: ''
    CUSTOM_DEPLOY_ARGUMENTS:
        required: false
        description: 'Comma-separated list of user-defined arguments for deployment'
    SKIP_BOOTSTRAP:
        required: false
        description: 'Skip running CDK bootstrap'
        default: 'false'
runs:
    using: 'node12'
    main: 'dist/index.js'
